import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { AuthContext } from "../../context/AuthContext";
import { useContext } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  let { loginStatus, serverURL } = useContext(AuthContext);
  const router = useRouter();
  const handleLogout = async () => {
    try {
      const response = await fetch(serverURL + "/logout", {
        credentials: "include",
      });
      const data = await response.json();
      console.log(data.message);
      router.push("/");
    } catch (err) {
      console.log(err);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleLogout}>Logout</button>
      <h1>Admin Dashboard</h1>
      <p>User is {loginStatus ? "" : "Not"} Logged in</p>
    </div>
  );
};

export default Home;
