import React from "react";
import JeletQnaAdder from "../../components/JELETQnaAdder";
import Head from "next/head";

export default function JELETQuestionAdder() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"
          user-scalable="0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JeletQnaAdder />
    </div>
  );
}
